"""Tool manifest + operation policy (v0.7.0 P1-1).

A ToolManifest is the declarative contract of a tool: what it does,
what side effects it produces, how it may be executed, and under what
constraints. It is the plugin contract unit: a future plugin registry
(v0.8+) is a bundle of manifests + executors; the tick kernel only
needs the manifest to enforce policy — it never inspects tool code.

An OperationPolicy is the deployment-time control surface: an admin
restricts a tool's blast radius (network, filesystem, wall time, output
size, approval) without touching tool code. Deny-by-default: a tool is
allowed only if listed in the policy.

Two-phase validation semantics (SPEC / v0.7.0 plan):
- PreValidate (Phase 6) consults manifest + policy: "is this attempt
  allowed to try?"
- CommitValidate (Phase 8) re-checks live preconditions: "is it still
  committable now?"
The manifest is used in both: PreValidate checks execution_class and
policy gates; CommitValidate cross-checks declared effect_types against
the actual staged effects.
"""

from __future__ import annotations

import hashlib
import json
import uuid
from dataclasses import dataclass, field
from enum import Enum
from functools import cached_property
from typing import Any

from my_team.models.llm import ToolDefinition
from my_team.sandbox_spec import DEFAULT_SECRET_KEYWORDS, SandboxConstraints
from my_team.transaction import EffectType


class ToolManifestError(ValueError):
    """Raised when a manifest or policy fails registration validation."""


class ExecutionClass(str, Enum):
    """How a tool may be executed (declared, enforced by the kernel).

    Classification honesty: LOCAL_PROCESS and SANDBOXED_PROCESS are
    DIFFERENT things. Only a tool with real isolation (read-only mount,
    network deny-by-default, resource limits) may declare
    SANDBOXED_PROCESS; a host subprocess with timeout + output
    truncation is LOCAL_PROCESS (see KANBAN/OPEN_ISSUE/OI-001.md).
    """

    PURE = "pure"
    # ^ No side effects, no I/O, deterministic output from input alone.
    READ_ONLY = "read_only"
    # ^ Reads system state (frozen snapshot view), never mutates.
    LOCAL_DETERMINISTIC = "local_deterministic"
    # ^ In-process computation, deterministic, no external effects.
    STAGED_MUTATION = "staged_mutation"
    # ^ Mutation staged as an effect, committed atomically in Commit
    #   phase; reversible via rollback.
    LOCAL_PROCESS = "local_process"
    # ^ Host subprocess with enforced timeout (process-group kill),
    #   output truncation, no shell, pinned cwd. NOT a sandbox: inherits
    #   env/PATH, no read-only mount, no network deny, no resource
    #   limits. The manifest's possible_side_effects must be declared.
    SANDBOXED_PROCESS = "sandboxed_process"
    # ^ External process in an isolated sandbox (read-only mount /
    #   temp workspace copy, network deny-by-default, resource limits,
    #   environment sanitisation — OI-001). The manifest MUST declare
    #   sandbox_constraints (the declarative spec); the execution
    #   backend enforces it and reports per-constraint (T16a). run_tests
    #   is the first builtin tool that qualifies.
    EXTERNAL_IRREVERSIBLE = "external_irreversible"
    # ^ External call that cannot be undone; must be declared
    #   irreversible and (typically) requires approval.


class RetryPolicy(str, Enum):
    """Retry policy for tool invocation failures."""

    NONE = "none"
    FIXED = "fixed"
    EXPONENTIAL = "exponential"


# Valid filesystem scope tokens for ToolManifest.filesystem_scopes.
FILESYSTEM_SCOPES = frozenset({
    "none",        # no filesystem access
    "private",     # agent's private workspace only
    "shared-kb",   # shared knowledge base only
    "workspace",   # simulation workspace (sandboxed)
    "system",      # host filesystem (explicitly discouraged)
})


@dataclass(frozen=True)
class ToolManifest:
    """Declarative contract of a tool. Registration validates it.

    v0.11（N1b，SPEC §5.1 工具面）新契约字段：

    - ``device_id``：声明该工具的设备标识（空 = 内核直接声明）；
    - ``capability``：受控 uuid（§5.1 设备动态向 Authority 注册）。
      缺省时按契约内容确定性派生（uuid5）——同一契约稳定同 uuid，
      契约任何字段变化即换 uuid（与 ``manifest_hash`` 一致）；显式
      提供时必须可解析为 uuid；
    - ``approval_policy``：何时需要人工审批的声明（自由文本，
      N 后续卡片解释执行；本卡仅承载）；
    - ``ingress_event_types``：该工具消费的 Ingress 事件类型声明
      （§5.11，本卡仅承载）；
    - ``egress``：出站通道/契约声明（如 "http"/"smtp"，§5.11）；
    - ``compensation_tool``：不可逆操作的补偿工具名（§6.4 补偿/
      对账路径，本卡仅承载）。
    """

    name: str
    version: str
    execution_class: ExecutionClass
    # JSON-Schema-ish dicts (kept as plain dicts: the kernel only needs
    # shape validation, not a full schema engine).
    input_schema: dict[str, Any] = field(default_factory=dict)
    output_schema: dict[str, Any] = field(default_factory=dict)
    description: str = ""
    # ^ Human/LLM-facing description of the tool (function-calling
    #   definition source; generated by manifest_to_tool_definition).
    required_inputs: tuple[str, ...] = ()
    # ^ Property names that must be present in the arguments. Must be a
    #   subset of input_schema keys (validated at registration).
    capabilities: tuple[str, ...] = ()
    effect_types: tuple[EffectType, ...] = ()
    # Documented (not kernel-enforced) side-effect possibilities for
    # LOCAL_PROCESS tools: e.g. "file_write_local", "process_spawn",
    # "possible_network". The kernel cannot observe everything an
    # un-sandboxed process does — this is the honest disclosure.
    possible_side_effects: tuple[str, ...] = ()
    deterministic: bool = True
    idempotent: bool = False
    reversible: bool = True
    requires_network: bool = False
    filesystem_scopes: tuple[str, ...] = ("none",)
    max_runtime_ms: int | None = None
    max_output_bytes: int | None = None
    supports_cancel: bool = False
    requires_approval: bool = False
    retry_policy: RetryPolicy = RetryPolicy.NONE
    sandbox_constraints: SandboxConstraints | None = None
    # ^ Declarative isolation spec for SANDBOXED_PROCESS tools (T16a):
    #   resource limits / network deny / read-only binds / environment
    #   sanitisation. Required for SANDBOXED_PROCESS, forbidden
    #   otherwise — the declaration is the contract the backend
    #   enforces (OI-001).
    # N1b 新契约（§5.1 工具面）：设备归属 + 受控 capability + 审批 /
    # Ingress / Egress / 补偿声明。
    device_id: str = ""
    capability: str = ""
    approval_policy: str = ""
    ingress_event_types: tuple[str, ...] = ()
    egress: str = ""
    compensation_tool: str = ""

    def __post_init__(self) -> None:
        errors: list[str] = []

        if not self.name or not self.name.strip():
            errors.append("name must be a non-empty string")
        if not self.version or not self.version.strip():
            errors.append("version must be a non-empty string")
        if not isinstance(self.input_schema, dict):
            errors.append("input_schema must be a dict")
        if not isinstance(self.output_schema, dict):
            errors.append("output_schema must be a dict")
        if not isinstance(self.description, str):
            errors.append("description must be a string")
        if not isinstance(self.required_inputs, tuple):
            errors.append("required_inputs must be a tuple of str")
        for ri in self.required_inputs:
            if not isinstance(ri, str):
                errors.append(f"required_inputs contains non-str: {ri!r}")
            elif ri not in self.input_schema:
                errors.append(
                    f"required_input '{ri}' is not a key of input_schema"
                )
        if not isinstance(self.effect_types, tuple):
            errors.append("effect_types must be a tuple of EffectType")
        for et in self.effect_types:
            if not isinstance(et, EffectType):
                errors.append(f"effect_types contains non-EffectType: {et!r}")
        for scope in self.filesystem_scopes:
            if scope not in FILESYSTEM_SCOPES:
                errors.append(f"invalid filesystem_scope: {scope!r}")
        if self.max_runtime_ms is not None and self.max_runtime_ms < 0:
            errors.append("max_runtime_ms must be >= 0")
        if self.max_output_bytes is not None and self.max_output_bytes < 0:
            errors.append("max_output_bytes must be >= 0")

        # N1b 新契约字段校验：ingress_event_types 必须为 str 元组；
        # capability 缺省按契约内容确定性派生（uuid5），显式给出必须
        # 可解析为 uuid（§5.1 受控 uuid）。
        if not isinstance(self.ingress_event_types, tuple):
            errors.append("ingress_event_types must be a tuple of str")
        for evt in self.ingress_event_types:
            if not isinstance(evt, str):
                errors.append(f"ingress_event_types contains non-str: {evt!r}")
        if self.capability:
            try:
                uuid.UUID(str(self.capability))
            except (ValueError, AttributeError, TypeError):
                errors.append(
                    f"capability must be a uuid, got {self.capability!r}"
                )
        else:
            object.__setattr__(self, "capability", self._derive_capability())

        # Execution-class coherence.
        if self.execution_class in {ExecutionClass.PURE, ExecutionClass.READ_ONLY}:
            if self.effect_types:
                errors.append(
                    f"{self.execution_class.value} tools cannot declare effect_types"
                )
        if self.execution_class is ExecutionClass.STAGED_MUTATION:
            if not self.effect_types:
                errors.append(
                    "STAGED_MUTATION tools must declare at least one effect_type"
                )
        if self.execution_class is ExecutionClass.PURE:
            if not self.deterministic:
                errors.append("PURE tools must be deterministic")
        if self.execution_class is ExecutionClass.EXTERNAL_IRREVERSIBLE:
            if self.reversible:
                errors.append(
                    "EXTERNAL_IRREVERSIBLE tools must declare reversible=False"
                )
        if self.execution_class is ExecutionClass.SANDBOXED_PROCESS:
            # T16a: a sandboxed tool MUST declare its isolation spec —
            # declaration is the contract the backend enforces; a
            # SANDBOXED_PROCESS without constraints is an unsupported
            # claim. Network is denied by the sandbox itself, so the
            # tool must not require it (deny-by-default).
            if self.sandbox_constraints is None:
                errors.append(
                    "SANDBOXED_PROCESS tools must declare "
                    "sandbox_constraints"
                )
            if self.requires_network:
                errors.append(
                    "SANDBOXED_PROCESS tools deny network by default "
                    "(requires_network must be False)"
                )
        elif self.sandbox_constraints is not None:
            errors.append(
                "sandbox_constraints is only valid for SANDBOXED_PROCESS "
                "tools"
            )

        if errors:
            raise ToolManifestError(
                f"Invalid manifest '{self.name}': " + "; ".join(errors)
            )

    def _derive_capability(self) -> str:
        """按契约内容（除 capability 自身）确定性派生受控 uuid（uuid5）。

        同一契约稳定同 capability；任何契约字段变化即换 uuid——与
        ``manifest_hash`` 同构，保证 ``manifest_hash`` 跨实例稳定
        （test_tool_protocol：同内容同哈希）。
        """
        basis = {
            name: getattr(self, name)
            for name in self.__dataclass_fields__
            if name != "capability"
        }
        digest = hashlib.sha256(
            json.dumps(
                basis, sort_keys=True, ensure_ascii=False,
                separators=(",", ":"), default=str,
            ).encode("utf-8")
        ).digest()
        return str(uuid.UUID(bytes=digest[:16], version=5))

    def declares_effect(self, effect_type: EffectType) -> bool:
        """Whether this manifest declares a given effect type."""
        return effect_type in self.effect_types

    @cached_property
    def manifest_hash(self) -> str:
        """sha256 over the canonical JSON of the full contract.

        Stable per manifest content: a version bump or any contract
        field change produces a different hash. ToolRequests carry it;
        it enters the audit trail and replay context (v0.8.0 P1-3).
        """
        payload = json.dumps(
            {
                name: getattr(self, name)
                for name in self.__dataclass_fields__
            },
            sort_keys=True, ensure_ascii=False, separators=(",", ":"),
            default=str,
        )
        return hashlib.sha256(payload.encode("utf-8")).hexdigest()


@dataclass(frozen=True)
class PolicyDecision:
    """Outcome of an OperationPolicy check against a manifest."""

    allowed: bool
    requires_approval: bool = False
    reason: str = ""


@dataclass(frozen=True)
class OperationPolicy:
    """Deployment-time control surface over tools. Deny-by-default."""

    allowed: frozenset[str] = frozenset()
    # ^ Tool names this deployment allows. A tool NOT listed is denied.
    requires_approval: frozenset[str] = frozenset()
    # ^ Tools whose invocation needs human approval before execution.
    max_wall_time_ms: int | None = None
    max_output_bytes: int | None = None
    network_access: bool = False
    filesystem_scope: str | None = None
    # ^ "private" | "shared-kb" | "workspace" | "system" | None (unrestricted)
    retry_policy: RetryPolicy | None = None
    reversible: bool = True
    # ^ False = irreversible tools are denied.

    def __post_init__(self) -> None:
        if self.filesystem_scope is not None and \
                self.filesystem_scope not in FILESYSTEM_SCOPES:
            raise ToolManifestError(
                f"invalid policy filesystem_scope: {self.filesystem_scope!r}"
            )
        if self.max_wall_time_ms is not None and self.max_wall_time_ms < 0:
            raise ToolManifestError("max_wall_time_ms must be >= 0")
        if self.max_output_bytes is not None and self.max_output_bytes < 0:
            raise ToolManifestError("max_output_bytes must be >= 0")
        if not self.requires_approval.issubset(self.allowed):
            raise ToolManifestError(
                "requires_approval must be a subset of allowed"
            )

    def decide(self, manifest: ToolManifest) -> PolicyDecision:
        """Check a tool manifest against this policy (deny-by-default).

        Returns allowed / denied / requires_approval with a reason.
        """
        if manifest.name not in self.allowed:
            return PolicyDecision(
                False, False,
                f"Tool '{manifest.name}' not in policy allowlist",
            )
        if manifest.name in self.requires_approval:
            return PolicyDecision(
                True, True, "Requires human approval per policy",
            )
        if not self.network_access and manifest.requires_network:
            return PolicyDecision(
                False, False,
                f"Tool '{manifest.name}' requires network; policy denies network",
            )
        if self.filesystem_scope and manifest.filesystem_scopes:
            scopes = set(manifest.filesystem_scopes)
            if "system" in scopes:
                return PolicyDecision(
                    False, False,
                    f"Tool '{manifest.name}' touches host filesystem "
                    f"(scope 'system'); policy allows '{self.filesystem_scope}'",
                )
            if scopes != {"none"} and self.filesystem_scope not in scopes:
                return PolicyDecision(
                    False, False,
                    f"Tool '{manifest.name}' scopes {sorted(scopes)} outside "
                    f"policy filesystem_scope '{self.filesystem_scope}'",
                )
        if (
            self.max_wall_time_ms is not None
            and manifest.max_runtime_ms is not None
            and manifest.max_runtime_ms > self.max_wall_time_ms
        ):
            return PolicyDecision(
                False, False,
                f"Tool '{manifest.name}' max_runtime_ms "
                f"{manifest.max_runtime_ms} exceeds policy cap "
                f"{self.max_wall_time_ms}",
            )
        if (
            self.max_output_bytes is not None
            and manifest.max_output_bytes is not None
            and manifest.max_output_bytes > self.max_output_bytes
        ):
            return PolicyDecision(
                False, False,
                f"Tool '{manifest.name}' max_output_bytes "
                f"{manifest.max_output_bytes} exceeds policy cap "
                f"{self.max_output_bytes}",
            )
        if not self.reversible and not manifest.reversible:
            return PolicyDecision(
                False, False,
                f"Tool '{manifest.name}' is irreversible; policy denies "
                "irreversible tools",
            )
        return PolicyDecision(True, False, "")


def builtin_manifests() -> dict[str, ToolManifest]:
    """Manifests for the v0.6.0 builtin tools (registered at startup).

    Execution-class mapping:
      read/ls          → READ_ONLY (frozen snapshot view)
      kb_read/kb_list/kb_search → READ_ONLY (v0.10 T8a, KB read side)
      write/kb_write   → STAGED_MUTATION (staged, committed atomically)
      send_email       → STAGED_MUTATION (outbox-staged; discarded on
                         rollback before delivery)
      delegate         → STAGED_MUTATION (TASK_CREATE + EMAIL_SEND)
    """
    read = ToolManifest(
        name="read",
        version="1.0.0",
        execution_class=ExecutionClass.READ_ONLY,
        description="Read a file from your private workspace",
        input_schema={
            "path": {"type": "string",
                     "description": "Path relative to your private workspace"},
        },
        required_inputs=("path",),
        output_schema={"content": {"type": "string"}},
        capabilities=("filesystem:read",),
        filesystem_scopes=("private",),
        deterministic=True,
        idempotent=True,
        max_output_bytes=1_000_000,
    )
    ls = ToolManifest(
        name="ls",
        version="1.0.0",
        execution_class=ExecutionClass.READ_ONLY,
        description="List files in your private workspace",
        input_schema={
            "path": {"type": "string",
                     "description": "Directory path relative to workspace"},
        },
        output_schema={"entries": {"type": "array"}},
        capabilities=("filesystem:list",),
        filesystem_scopes=("private",),
        deterministic=True,
        idempotent=True,
        max_output_bytes=1_000_000,
    )
    write = ToolManifest(
        name="write",
        version="1.0.0",
        execution_class=ExecutionClass.STAGED_MUTATION,
        description="Write a file to your private workspace",
        input_schema={
            "path": {"type": "string",
                     "description": "Path relative to workspace"},
            "content": {"type": "string", "description": "File content"},
        },
        required_inputs=("path", "content"),
        output_schema={"staged": {"type": "boolean"}},
        capabilities=("filesystem:write",),
        effect_types=(EffectType.FILE_WRITE,),
        filesystem_scopes=("private",),
        deterministic=True,
        idempotent=True,
        reversible=True,
    )
    kb_write = ToolManifest(
        name="kb_write",
        version="1.0.0",
        execution_class=ExecutionClass.STAGED_MUTATION,
        description="Write an entry to the shared knowledge base",
        input_schema={
            "path": {"type": "string",
                     "description": "KB entry path"},
            "content": {"type": "string", "description": "Entry content"},
            "expected_version": {"type": "integer",
                                 "description": "Expected entry version for "
                                                 "optimistic locking"},
        },
        required_inputs=("path", "content"),
        output_schema={"staged": {"type": "boolean"}},
        capabilities=("kb:write",),
        effect_types=(EffectType.KB_WRITE,),
        filesystem_scopes=("shared-kb",),
        deterministic=True,
        idempotent=False,  # versioned — a stale write fails, not deduped
        reversible=True,
    )
    send_email = ToolManifest(
        name="send_email",
        version="1.0.0",
        execution_class=ExecutionClass.STAGED_MUTATION,
        description="Send an email to another agent (attachments are "
                    "structured refs — carried on the email, never copied)",
        input_schema={
            "to": {"type": "array", "items": {"type": "string"},
                   "description": "Recipient agent ids"},
            "subject": {"type": "string", "description": "Email subject"},
            "body": {"type": "string", "description": "Email body"},
            "attachments": {
                "type": "array",
                "items": {"type": "object"},
                "description": "Attachment refs: {ref_type, path, version, "
                               "hash, size, mime} (e.g. ref_type=shared_kb "
                               "with a KB path@version)",
            },
        },
        required_inputs=("to", "subject", "body"),
        output_schema={"staged": {"type": "boolean"}},
        capabilities=("email:send",),
        effect_types=(EffectType.EMAIL_SEND,),
        filesystem_scopes=("none",),
        deterministic=True,
        idempotent=True,  # outbox idempotency keys dedupe
        reversible=True,  # discarded on rollback before delivery
        max_output_bytes=100_000,
    )
    delegate = ToolManifest(
        name="delegate",
        version="1.0.0",
        execution_class=ExecutionClass.STAGED_MUTATION,
        description="Delegate a task to a direct child agent",
        input_schema={
            "recipient_agent_id": {"type": "string",
                                   "description": "Direct child agent to "
                                                   "delegate to"},
            "task_title": {"type": "string", "description": "Task title"},
            "task_description": {"type": "string",
                                 "description": "Task description"},
        },
        required_inputs=("recipient_agent_id", "task_title"),
        output_schema={"task_id": {"type": "string"}, "staged": {"type": "boolean"}},
        capabilities=("task:delegate",),
        effect_types=(EffectType.TASK_CREATE, EffectType.EMAIL_SEND),
        filesystem_scopes=("none",),
        deterministic=True,
        idempotent=False,
        reversible=True,
    )
    # v0.7.0 restricted tools (P1-3) — the safe set that precedes Bash
    # (see KANBAN/OPEN_ISSUE/OI-001.md).
    apply_patch = ToolManifest(
        name="apply_patch",
        version="1.0.0",
        execution_class=ExecutionClass.STAGED_MUTATION,
        description="Apply a patch to a file in your private workspace",
        input_schema={
            "path": {"type": "string",
                     "description": "Path relative to workspace"},
            "patch": {"type": "string",
                      "description": "Unified diff patch to apply"},
        },
        required_inputs=("path", "patch"),
        output_schema={"staged": {"type": "boolean"}},
        capabilities=("filesystem:patch",),
        effect_types=(EffectType.FILE_PATCH,),
        filesystem_scopes=("private",),
        deterministic=True,
        idempotent=False,   # context-dependent — conflict → reject
        reversible=True,    # rolled back via file_previous like FILE_WRITE
        max_output_bytes=1_000_000,
    )
    # T16a: SANDBOXED_PROCESS — real isolation (was LOCAL_PROCESS
    # since v0.7.0). Running tests executes untrusted code (conftest,
    # plugins, imports, subprocesses, possible network), so the sandbox
    # is: temp workspace COPY as cwd (host tree untouched — T17
    # by-product), network deny-by-default (netns), resource limits
    # (CPU/memory/processes/file size), environment sanitisation
    # (sitecustomize/PYTHONPATH/PATH/secret stripped, GIT_* pinned).
    # sandbox_constraints is the DECLARED spec; the backend enforces
    # it and reports per-constraint in sandbox_report.
    run_tests = ToolManifest(
        name="run_tests",
        version="2.0.0",
        execution_class=ExecutionClass.SANDBOXED_PROCESS,
        description="Run tests in the workspace and report results",
        input_schema={
            "test_path": {"type": "string",
                          "description": "Path to test file or directory"},
        },
        required_inputs=("test_path",),
        output_schema={
            "success": {"type": "boolean"},
            "stdout": {"type": "string"},
            "stderr": {"type": "string"},
            "exit_code": {"type": "integer"},
        },
        capabilities=("test:run",),
        effect_types=(),
        possible_side_effects=(),
        filesystem_scopes=("workspace",),
        deterministic=False,    # depends on test results
        idempotent=True,
        reversible=True,
        requires_network=False,  # sandbox denies network (deny-by-default)
        max_runtime_ms=60_000,
        max_output_bytes=200_000,
        supports_cancel=True,   # physical kill of the process group
                                # (v0.8.0 P2-10)
        sandbox_constraints=SandboxConstraints(
            cpu_seconds=60,
            memory_bytes=512 * 1024 * 1024,
            max_processes=64,
            max_file_bytes=16 * 1024 * 1024,
            strip_env=("PYTHONPATH", "PYTHONHOME", "PYTHONSTARTUP",
                       "PYTHONUSERBASE"),
            strip_env_keywords=DEFAULT_SECRET_KEYWORDS,
            minimal_path=True,
            pin_git_env=True,
            deny_network=True,
            isolated_mount=True,
        ),
    )
    git_diff = ToolManifest(
        name="git_diff",
        version="1.0.0",
        execution_class=ExecutionClass.READ_ONLY,
        description="Show the diff of the workspace git repository",
        input_schema={
            "path": {"type": "string",
                     "description": "Path to show diff for"},
        },
        required_inputs=("path",),
        output_schema={"stdout": {"type": "string"}},
        capabilities=("git:diff",),
        effect_types=(),
        filesystem_scopes=("workspace",),
        deterministic=False,    # output depends on repo state
        idempotent=True,
        max_runtime_ms=10_000,
        max_output_bytes=200_000,
    )
    git_status = ToolManifest(
        name="git_status",
        version="1.0.0",
        execution_class=ExecutionClass.READ_ONLY,
        description="Show the status of the workspace git repository",
        input_schema={},
        output_schema={"stdout": {"type": "string"}},
        capabilities=("git:status",),
        effect_types=(),
        filesystem_scopes=("workspace",),
        deterministic=False,
        idempotent=True,
        max_runtime_ms=10_000,
        max_output_bytes=200_000,
    )
    # v0.8.0 P1-7: python execution levels L0/L1 (SPEC §8.7 执行等级).
    # Honest classification: LOCAL_PROCESS — capability reduction +
    # process isolation prevent ACCIDENTS (hallucinated code, wrong
    # arguments, infinite loops), NOT malicious escapes. possible_
    # side_effects disclose the residual surface ("possible_fs_access":
    # introspection can in principle reach interpreter internals).
    python_compute = ToolManifest(
        name="python_compute",
        version="1.0.0",
        execution_class=ExecutionClass.LOCAL_PROCESS,
        description="Run a pure Python computation (no filesystem side effects)",
        input_schema={
            "code": {"type": "string", "description": "Python code to execute"},
            "inputs": {"type": "object", "description": "Input values"},
            "allowed_modules": {"type": "array",
                                "description": "Modules allowed to import"},
        },
        required_inputs=("code",),
        output_schema={"result": {"type": "object"}},
        capabilities=("python:compute",),
        effect_types=(),
        possible_side_effects=("possible_fs_access", "possible_process_spawn"),
        filesystem_scopes=("none",),
        deterministic=False,
        idempotent=True,
        reversible=True,
        requires_network=False,
        max_runtime_ms=10_000,
        max_output_bytes=200_000,
        supports_cancel=True,
    )
    python_transform = ToolManifest(
        name="python_transform",
        version="1.0.0",
        execution_class=ExecutionClass.LOCAL_PROCESS,
        description="Run a Python transformation over workspace files",
        input_schema={
            "code": {"type": "string", "description": "Python code to execute"},
            "inputs": {"type": "object", "description": "Input values"},
            "input_files": {"type": "object",
                            "description": "File inputs (path → content)"},
            "allowed_modules": {"type": "array",
                                "description": "Modules allowed to import"},
        },
        required_inputs=("code",),
        output_schema={
            "result": {"type": "object"},
            "artifacts": {"type": "array"},
        },
        capabilities=("python:transform",),
        effect_types=(),
        possible_side_effects=("file_write_local", "possible_fs_access"),
        filesystem_scopes=("workspace",),
        deterministic=False,
        idempotent=False,
        reversible=True,
        requires_network=False,
        max_runtime_ms=30_000,
        max_output_bytes=200_000,
        supports_cancel=True,
    )
    # v0.10 T8a: KB read-side tools (SharedKB 读侧能力 — OI-004 §1.5 此前
    # 只能写不能读). All READ_ONLY: deterministic, idempotent, no effects,
    # no pending-op path — same class as read/ls. Every read goes through
    # PermissionEngine (SPEC §7.2 硬性要求).
    kb_read = ToolManifest(
        name="kb_read",
        version="1.0.0",
        execution_class=ExecutionClass.READ_ONLY,
        description="Read an entry from the shared knowledge base",
        input_schema={
            "path": {"type": "string", "description": "KB entry path"},
        },
        required_inputs=("path",),
        output_schema={
            "content": {"type": "string"},
            "version": {"type": "integer"},
            "last_modified_by": {"type": "string"},
            "last_modified_at_tick": {"type": "integer"},
        },
        capabilities=("kb:read",),
        filesystem_scopes=("shared-kb",),
        deterministic=True,
        idempotent=True,
        max_output_bytes=1_000_000,
    )
    kb_list = ToolManifest(
        name="kb_list",
        version="1.0.0",
        execution_class=ExecutionClass.READ_ONLY,
        description="List shared knowledge base paths under a prefix",
        input_schema={
            "base_path": {"type": "string",
                          "description": "KB prefix to list under ('' = all readable)"},
        },
        output_schema={"paths": {"type": "array", "items": {"type": "string"}}},
        capabilities=("kb:list",),
        filesystem_scopes=("shared-kb",),
        deterministic=True,
        idempotent=True,
        max_output_bytes=200_000,
    )
    kb_search = ToolManifest(
        name="kb_search",
        version="1.0.0",
        execution_class=ExecutionClass.READ_ONLY,
        description="Keyword search readable shared knowledge base entries "
                    "(case-insensitive substring on path or content)",
        input_schema={
            "query": {"type": "string", "description": "Search keywords"},
            "base_path": {"type": "string",
                          "description": "Scope the search to a KB prefix"},
            "limit": {"type": "integer", "description": "Max hits (default 20)"},
        },
        required_inputs=("query",),
        output_schema={
            "results": {"type": "array", "items": {"type": "object"}},
        },
        capabilities=("kb:search",),
        filesystem_scopes=("shared-kb",),
        deterministic=True,
        idempotent=True,
        max_output_bytes=200_000,
    )
    # v0.10 T10: typed record mutations — staged effects, invariant-checked
    # at Commit. STAGED_MUTATION: an invariant violation is a DETERMINISTIC
    # business failure (local FAILED over the whole group), not a rollback.
    record_upsert = ToolManifest(
        name="record_upsert",
        version="1.0.0",
        execution_class=ExecutionClass.STAGED_MUTATION,
        description="Upsert a typed record (invariant-checked at commit)",
        input_schema={
            "record_type": {"type": "string",
                            "description": "Registered record type (e.g. sku)"},
            "key": {"type": "string", "description": "Record key"},
            "record": {"type": "object", "description": "Record fields"},
        },
        required_inputs=("record_type", "key", "record"),
        output_schema={"staged": {"type": "boolean"}},
        capabilities=("record:upsert",),
        effect_types=(EffectType.RECORD_UPSERT,),
        filesystem_scopes=("none",),
        deterministic=True,
        idempotent=False,  # upsert by key — a repeated call re-writes
        reversible=True,   # undone via prior-record restore (T10/T18)
        max_output_bytes=100_000,
    )
    record_delta = ToolManifest(
        name="record_delta",
        version="1.0.0",
        execution_class=ExecutionClass.STAGED_MUTATION,
        description="Apply a numeric delta to a record field "
                    "(e.g. stock movement; invariants checked on the result)",
        input_schema={
            "record_type": {"type": "string",
                            "description": "Registered record type"},
            "key": {"type": "string", "description": "Record key"},
            "field": {"type": "string",
                      "description": "Numeric field to adjust"},
            "delta": {"type": "number", "description": "Delta (signed)"},
        },
        required_inputs=("record_type", "key", "field", "delta"),
        output_schema={"staged": {"type": "boolean"}},
        capabilities=("record:delta",),
        effect_types=(EffectType.RECORD_DELTA,),
        filesystem_scopes=("none",),
        deterministic=True,
        idempotent=False,
        reversible=True,
        max_output_bytes=100_000,
    )
    # ------------------------------------------------------------------
    # N4-4 记忆工具集（CONSOLIDATING 工具面收窄目标，SPEC §4.4）。
    # STAGED_MUTATION：内核执行，动作 = Journal effect（可审计可回滚）。
    # 记忆归属 Agent 引擎（§4.2），工具面声明 device_id 为空（内核直管）。
    # ------------------------------------------------------------------
    memory_fold = ToolManifest(
        name="memory_fold",
        version="1.0.0",
        execution_class=ExecutionClass.STAGED_MUTATION,
        description="Fold a memory entry's version chain into one condensed "
                    "entry (consolidation)",
        input_schema={
            "entry_id": {"type": "string", "description": "Entry to fold"},
            "content_text": {"type": "string",
                             "description": "Condensed content text"},
            "title": {"type": "string", "description": "New title (optional)"},
            "memory_points": {"type": "array", "items": {"type": "string"},
                              "description": "New trigger words (optional)"},
        },
        required_inputs=("entry_id", "content_text"),
        output_schema={"entry_id": {"type": "string"},
                       "version": {"type": "integer"}},
        capabilities=("memory:fold",),
        effect_types=(EffectType.MEMORY_ENTRY_FOLD,),
        filesystem_scopes=("none",),
        deterministic=True,
        idempotent=False,
        reversible=True,
    )
    memory_promote = ToolManifest(
        name="memory_promote",
        version="1.0.0",
        execution_class=ExecutionClass.STAGED_MUTATION,
        description="Promote an entry/note into a long-term skill entry "
                    "(optionally linked to a task result as provenance)",
        input_schema={
            "entry_id": {"type": "string",
                         "description": "Source entry to promote (optional)"},
            "title": {"type": "string", "description": "Skill title (optional)"},
            "sop_text": {"type": "string", "description": "SOP text (optional)"},
            "applies_to": {"type": "array", "items": {"type": "string"},
                           "description": "Applicable scenarios"},
            "memory_points": {"type": "array", "items": {"type": "string"},
                              "description": "Trigger words"},
            "task_id": {"type": "string",
                        "description": "Task id for result provenance"},
            "outcome": {"type": "string",
                        "description": "Outcome label (completed/failed/...)"},
            "note": {"type": "string", "description": "Provenance note"},
        },
        required_inputs=(),
        output_schema={"entry_id": {"type": "string"},
                       "version": {"type": "integer"}},
        capabilities=("memory:promote",),
        effect_types=(EffectType.MEMORY_ENTRY_WRITE,),
        filesystem_scopes=("none",),
        deterministic=True,
        idempotent=False,
        reversible=True,
    )
    memory_edit = ToolManifest(
        name="memory_edit",
        version="1.0.0",
        execution_class=ExecutionClass.STAGED_MUTATION,
        description="Edit a memory entry (appends a new immutable version)",
        input_schema={
            "entry_id": {"type": "string", "description": "Entry to edit"},
            "content_text": {"type": "string",
                             "description": "New content text (optional)"},
            "title": {"type": "string", "description": "New title (optional)"},
            "memory_points": {"type": "array", "items": {"type": "string"},
                              "description": "New trigger words (optional)"},
        },
        required_inputs=("entry_id",),
        output_schema={"entry_id": {"type": "string"},
                       "version": {"type": "integer"}},
        capabilities=("memory:edit",),
        effect_types=(EffectType.MEMORY_ENTRY_WRITE,),
        filesystem_scopes=("none",),
        deterministic=True,
        idempotent=False,
        reversible=True,
    )
    memory_retag = ToolManifest(
        name="memory_retag",
        version="1.0.0",
        execution_class=ExecutionClass.STAGED_MUTATION,
        description="Retag a memory entry (maintain its trigger words, "
                    "appends a new version)",
        input_schema={
            "entry_id": {"type": "string", "description": "Entry to retag"},
            "memory_points": {"type": "array", "items": {"type": "string"},
                              "description": "New trigger words (full replace)"},
        },
        required_inputs=("entry_id", "memory_points"),
        output_schema={"entry_id": {"type": "string"},
                       "version": {"type": "integer"}},
        capabilities=("memory:retag",),
        effect_types=(EffectType.MEMORY_ENTRY_WRITE,),
        filesystem_scopes=("none",),
        deterministic=True,
        idempotent=False,
        reversible=True,
    )
    memory_evict = ToolManifest(
        name="memory_evict",
        version="1.0.0",
        execution_class=ExecutionClass.STAGED_MUTATION,
        description="Evict a memory entry from the working set (removes "
                    "from store; journal effect is reversible)",
        input_schema={
            "entry_id": {"type": "string", "description": "Entry to evict"},
        },
        required_inputs=("entry_id",),
        output_schema={"entry_id": {"type": "string"}},
        capabilities=("memory:evict",),
        effect_types=(EffectType.MEMORY_ENTRY_EVICT,),
        filesystem_scopes=("none",),
        deterministic=True,
        idempotent=False,
        reversible=True,
    )
    memory_pin = ToolManifest(
        name="memory_pin",
        version="1.0.0",
        execution_class=ExecutionClass.STAGED_MUTATION,
        description="Pin a memory entry: merge its title and trigger words "
                    "into the controlled query terms (protect from recall "
                    "degradation)",
        input_schema={
            "entry_id": {"type": "string", "description": "Entry to pin"},
        },
        required_inputs=("entry_id",),
        output_schema={"entry_id": {"type": "string"},
                       "added_terms": {"type": "array"}},
        capabilities=("memory:pin",),
        effect_types=(EffectType.MEMORY_PIN,),
        filesystem_scopes=("none",),
        deterministic=True,
        idempotent=False,
        reversible=True,
    )
    return {
        m.name: m
        for m in (
            read, ls, write, kb_write, send_email, delegate,
            apply_patch, run_tests, git_diff, git_status,
            python_compute, python_transform,
            kb_read, kb_list, kb_search,
            record_upsert, record_delta,
            memory_fold, memory_promote, memory_edit,
            memory_retag, memory_evict, memory_pin,
        )
    }


def manifest_to_tool_definition(manifest: ToolManifest) -> ToolDefinition:
    """Generate an LLM function-calling definition from a ToolManifest.

    This is the single source for tool definitions: PromptTemplates
    renders definitions exclusively through this generator (no
    hand-written tool tables). ``parameters`` is a JSON Schema object
    built from ``input_schema`` (properties) + ``required_inputs``.
    """
    parameters: dict[str, Any] = {
        "type": "object",
        "properties": dict(manifest.input_schema),
    }
    if manifest.required_inputs:
        parameters["required"] = [
            k for k in manifest.required_inputs if k in manifest.input_schema
        ]
    return ToolDefinition(
        name=manifest.name,
        description=manifest.description,
        parameters=parameters,
    )
